[package]
name = "tele-decode"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
num-complex = "0.4"
hackrfone = "0.2.3"
itertools = "0.12"

[profile.release]
debug = true
#lto = true
#opt-level = 1
