workspace = { members = ["async-libhackrf", "telemega"] }

[package]
name = "tele-decode"
version = "0.1.0"
edition = "2021"

[dependencies]
#telemega = { path = "telemega" }
lora = { path = "lora" }
#serde_json = "1.0"
#rocket = "0.5.0"
#webbrowser = "0.8"
