[package]
name = "async-libhackrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nusb = "0.1.7"
smol = "2.0.0"